namespace O9K.ItemManager.Modules.AbilityLeveling.Names
{
    using System.Collections.Generic;

    using Core.Logger;

    internal class Abilities
    {
        //// generate ability names
        //public Abilities()
        //{
        //    Console.Clear();
        //    var duplicates = new HashSet<string>();
        //    foreach (var hero in Enum.GetNames(typeof(HeroId)))
        //    {
        //        for (var i = 1; i <= 30; i++)
        //        {
        //            try
        //            {
        //                var name = Game.FindKeyValues(hero + "/Ability" + i, KeyValueSource.Hero).StringValue;
        //                var displayName = LocalizationHelper.Localize(Loc.DOTA_Tooltip_Ability_STRING, name);
        //                if (displayName[0] == '#' || !duplicates.Add(name))
        //                {
        //                    continue;
        //                }
        //                var match = Regex.Match(displayName, @"\{[^:]:([^}]*)\}");
        //                while (match.Success)
        //                {
        //                    var replace = match.Groups[0].Value;
        //                    var dataKey = match.Groups[1].Value;
        //                    var value = Ability.GetAbilityDataByName(name)
        //                        .AbilitySpecialData.First(x => x.Name == dataKey)
        //                        .Value.ToString();
        //                    displayName = displayName.Replace(replace, value);
        //                    match = match.NextMatch();
        //                }
        //                Console.WriteLine("{ \"" + name + "\", \"" + displayName + "\" },");
        //            }
        //            catch
        //            {
        //            }
        //        }
        //    }
        //}

        // ReSharper disable StringLiteralTypo
        private readonly Dictionary<string, string> names = new Dictionary<string, string>
        {
            { "antimage_mana_break", "Mana Break" },
            { "antimage_blink", "Blink" },
            { "antimage_counterspell", "Counterspell" },
            { "antimage_mana_void", "Mana Void" },
            { "special_bonus_strength_10", "+10 Strength" },
            { "special_bonus_attack_speed_15", "+15 Attack Speed" },
            { "special_bonus_unique_antimage_3", "+325 Blink Cast Range" },
            { "special_bonus_agility_12", "+12 Agility" },
            { "special_bonus_unique_antimage_5", "Blink Uncontrollable Illusion" },
            { "special_bonus_unique_antimage", "-2s Blink Cooldown" },
            { "special_bonus_unique_antimage_4", "+20% Counterspell Magic Resistance" },
            { "special_bonus_unique_antimage_2", "-45s Mana Void Cooldown" },
            { "axe_berserkers_call", "Berserker's Call" },
            { "axe_battle_hunger", "Battle Hunger" },
            { "axe_counter_helix", "Counter Helix" },
            { "axe_culling_blade", "Culling Blade" },
            { "special_bonus_strength_8", "+8 Strength" },
            { "special_bonus_movement_speed_20", "+20 Movement Speed" },
            { "special_bonus_mp_regen_2", "+2 Mana Regen" },
            { "special_bonus_attack_speed_35", "+35 Attack Speed" },
            { "special_bonus_hp_regen_20", "+20 Health Regen" },
            { "special_bonus_unique_axe_3", "Attacking Procs Counter Helix" },
            { "special_bonus_unique_axe_2", "+100 Berserker's Call AoE" },
            { "special_bonus_unique_axe", "+100 Battle Hunger DPS" },
            { "bane_nightmare", "Nightmare" },
            { "bane_brain_sap", "Brain Sap" },
            { "bane_enfeeble", "Enfeeble" },
            { "bane_fiends_grip", "Fiend's Grip" },
            { "bane_nightmare_end", "Nightmare End" },
            { "special_bonus_armor_6", "+6 Armor" },
            { "special_bonus_magic_resistance_15", "+15% Magic Resistance" },
            { "special_bonus_spell_amplify_7", "+7% Spell Amplification" },
            { "special_bonus_cast_range_125", "+125 Cast Range" },
            { "special_bonus_unique_bane_5", "-3s Nightmare Cooldown" },
            { "special_bonus_movement_speed_40", "+40 Movement Speed" },
            { "special_bonus_unique_bane_2", "+200 Brain Sap Damage/Heal" },
            { "special_bonus_unique_bane_3", "+5.5s Fiend's Grip Duration" },
            { "bloodseeker_bloodrage", "Bloodrage" },
            { "bloodseeker_blood_bath", "Blood Rite" },
            { "bloodseeker_thirst", "Thirst" },
            { "bloodseeker_rupture", "Rupture" },
            { "special_bonus_attack_speed_20", "+20 Attack Speed" },
            { "special_bonus_armor_5", "+5 Armor" },
            { "special_bonus_hp_225", "+225 Health" },
            { "special_bonus_unique_bloodseeker_2", "+60 Blood Rite Damage" },
            { "special_bonus_unique_bloodseeker_3", "+475 Rupture Cast Range" },
            { "special_bonus_lifesteal_20", "20% Lifesteal" },
            { "special_bonus_unique_bloodseeker", "-5s Blood Rite Cooldown" },
            { "special_bonus_unique_bloodseeker_4", "+14 Max Thirst MS" },
            { "crystal_maiden_crystal_nova", "Crystal Nova" },
            { "crystal_maiden_frostbite", "Frostbite" },
            { "crystal_maiden_brilliance_aura", "Arcane Aura" },
            { "crystal_maiden_freezing_field", "Freezing Field" },
            { "special_bonus_hp_200", "+200 Health" },
            { "special_bonus_cast_range_75", "+75 Cast Range" },
            { "special_bonus_unique_crystal_maiden_4", "+8% Magic Resistance Arcane Aura" },
            { "special_bonus_unique_crystal_maiden_5", "-2s Crystal Nova Cooldown" },
            { "special_bonus_attack_speed_200", "+200 Attack Speed" },
            { "special_bonus_unique_crystal_maiden_3", "+50 Freezing Field Damage" },
            { "special_bonus_unique_crystal_maiden_1", "+1.25s Frostbite Duration" },
            { "special_bonus_unique_crystal_maiden_2", "+240 Crystal Nova Damage" },
            { "drow_ranger_frost_arrows", "Frost Arrows" },
            { "drow_ranger_wave_of_silence", "Gust" },
            { "drow_ranger_multishot", "Multishot" },
            { "drow_ranger_marksmanship", "Marksmanship" },
            { "special_bonus_unique_drow_ranger_5", "+40% Gust Blind" },
            { "special_bonus_all_stats_5", "+5 All Stats" },
            { "special_bonus_agility_10", "+10 Agility" },
            { "special_bonus_unique_drow_ranger_1", "+28% Multishot Damage" },
            { "special_bonus_unique_drow_ranger_4", "+2.5s Gust Silence Duration" },
            { "special_bonus_unique_drow_ranger_3", "+12 Marksmanship Chance" },
            { "special_bonus_cooldown_reduction_30", "30% Cooldown Reduction" },
            { "earthshaker_fissure", "Fissure" },
            { "earthshaker_enchant_totem", "Enchant Totem" },
            { "earthshaker_aftershock", "Aftershock" },
            { "earthshaker_echo_slam", "Echo Slam" },
            { "special_bonus_attack_damage_25", "+25 Damage" },
            { "special_bonus_mp_200", "+200 Mana" },
            { "special_bonus_movement_speed_25", "+25 Movement Speed" },
            { "special_bonus_unique_earthshaker_2", "+40 Echo Damage" },
            { "special_bonus_unique_earthshaker_3", "+320 Fissure Range" },
            { "special_bonus_magic_resistance_40", "+40% Magic Resistance" },
            { "special_bonus_unique_earthshaker", "-1.5s Enchant Totem Cooldown" },
            { "juggernaut_blade_fury", "Blade Fury" },
            { "juggernaut_healing_ward", "Healing Ward" },
            { "juggernaut_blade_dance", "Blade Dance" },
            { "juggernaut_swift_slash", "Swiftslash" },
            { "juggernaut_omni_slash", "Omnislash" },
            { "special_bonus_unique_juggernaut_4", "+80 Blade Fury Movement Speed" },
            { "special_bonus_armor_8", "+8 Armor" },
            { "special_bonus_unique_juggernaut_3", "+100 Blade Fury DPS" },
            { "special_bonus_hp_475", "+475 Health" },
            { "special_bonus_unique_juggernaut_2", "+1s Omnislash Duration" },
            { "mirana_starfall", "Starstorm" },
            { "mirana_arrow", "Sacred Arrow" },
            { "mirana_leap", "Leap" },
            { "mirana_invis", "Moonlight Shadow" },
            { "special_bonus_attack_damage_12", "+12 Damage" },
            { "special_bonus_hp_150", "+150 Health" },
            { "special_bonus_unique_mirana_3", "-3.5s Sacred Arrow cooldown" },
            { "special_bonus_unique_mirana_1", "+65 Leap Attack Speed" },
            { "special_bonus_spell_amplify_10", "+10% Spell Amplification" },
            { "special_bonus_mana_break_20", "+20 Mana Break" },
            { "special_bonus_unique_mirana_2", "+2 Multishot Sacred Arrows" },
            { "special_bonus_unique_mirana_4", "-60 Moonlight Shadow Cooldown" },
            { "morphling_waveform", "Waveform" },
            { "morphling_adaptive_strike_agi", "Adaptive Strike (Agility)" },
            { "morphling_adaptive_strike_str", "Adaptive Strike (Strength)" },
            { "morphling_morph_agi", "Attribute Shift (Agility Gain)" },
            { "morphling_morph_str", "Attribute Shift (Strength Gain)" },
            { "morphling_replicate", "Morph" },
            { "morphling_morph_replicate", "Morph Replicate" },
            { "special_bonus_unique_morphling_1", "+275 Waveform Range" },
            { "special_bonus_unique_morphling_8", "+16s Morph Duration" },
            { "special_bonus_attack_speed_30", "+30 Attack Speed" },
            { "special_bonus_cooldown_reduction_12", "12% Cooldown Reduction" },
            { "special_bonus_unique_morphling_4", "Waveform Attacks Targets" },
            { "special_bonus_unique_morphling_6", "2 Waveform Charges" },
            { "special_bonus_unique_morphling_3", "+3 Multishot Adaptive Strike" },
            { "nevermore_shadowraze1", "Shadowraze" },
            { "nevermore_shadowraze2", "Shadowraze" },
            { "nevermore_shadowraze3", "Shadowraze" },
            { "nevermore_necromastery", "Necromastery" },
            { "nevermore_dark_lord", "Presence of the Dark Lord" },
            { "nevermore_requiem", "Requiem of Souls" },
            { "special_bonus_spell_amplify_6", "+6% Spell Amplification" },
            { "special_bonus_unique_nevermore_3", "Presence Aura Affects Building" },
            { "special_bonus_unique_nevermore_1", "+2 Damage Per Soul" },
            { "special_bonus_unique_nevermore_2", "+120 Shadowraze Damage" },
            { "special_bonus_unique_nevermore_5", "-4 Presence Aura Armor" },
            { "phantom_lancer_spirit_lance", "Spirit Lance" },
            { "phantom_lancer_doppelwalk", "Doppelganger" },
            { "phantom_lancer_phantom_edge", "Phantom Rush" },
            { "phantom_lancer_juxtapose", "Juxtapose" },
            { "special_bonus_evasion_16", "16% Evasion" },
            { "special_bonus_unique_phantom_lancer_2", "+100 Spirit Lance Damage" },
            { "special_bonus_unique_phantom_lancer", "+400 Phantom Rush Range" },
            { "special_bonus_unique_phantom_lancer_3", "+5 Max Juxtapose Illusions" },
            { "special_bonus_unique_phantom_lancer_4", "-4s Doppelganger CD" },
            { "special_bonus_24_crit_2", "+24% Critical Strike (200%)" },
            { "puck_illusory_orb", "Illusory Orb" },
            { "puck_waning_rift", "Waning Rift" },
            { "puck_phase_shift", "Phase Shift" },
            { "puck_ethereal_jaunt", "Ethereal Jaunt" },
            { "puck_dream_coil", "Dream Coil" },
            { "special_bonus_cast_range_150", "+150 Cast Range" },
            { "special_bonus_spell_amplify_12", "+12% Spell Amplification" },
            { "special_bonus_unique_puck_5", "Phase Shift Attack" },
            { "special_bonus_unique_puck_2", "-7s Waning Rift Cooldown" },
            { "special_bonus_unique_puck", "+50% Illusory Orb Distance/Speed" },
            { "special_bonus_unique_puck_6", "+350 Waning Rift AoE and Range" },
            { "special_bonus_unique_puck_3", "Dream Coil Rapid Fire" },
            { "pudge_meat_hook", "Meat Hook" },
            { "pudge_rot", "Rot" },
            { "pudge_flesh_heap", "Flesh Heap" },
            { "pudge_eject", "Eject" },
            { "pudge_dismember", "Dismember" },
            { "special_bonus_armor_4", "+4 Armor" },
            { "special_bonus_unique_pudge_2", "+28 Rot Damage" },
            { "special_bonus_spell_lifesteal_10", "10% Spell Lifesteal" },
            { "special_bonus_unique_pudge_4", "-16% Rot Slow" },
            { "special_bonus_unique_pudge_6", "+0.8s Dismember Duration" },
            { "special_bonus_unique_pudge_5", "-4 Meat Hook Cooldown" },
            { "special_bonus_unique_pudge_3", "1.8x Dismember Damage/Heal" },
            { "special_bonus_unique_pudge_1", "+1.5 Flesh Heap Stack Str" },
            { "razor_plasma_field", "Plasma Field" },
            { "razor_static_link", "Static Link" },
            { "razor_unstable_current", "Storm Surge" },
            { "razor_eye_of_the_storm", "Eye of the Storm" },
            { "special_bonus_hp_175", "+175 Health" },
            { "special_bonus_agility_8", "+8 Agility" },
            { "special_bonus_unique_razor", "+5 Static Link Damage Steal" },
            { "special_bonus_strength_12", "+12 Strength" },
            { "special_bonus_unique_razor_2", "-0.1 Eye of the Storm Strike Interval" },
            { "special_bonus_attack_speed_80", "+80 Attack Speed" },
            { "special_bonus_unique_razor_4", "+180 Eye of the Storm Passive Damage" },
            { "sandking_burrowstrike", "Burrowstrike" },
            { "sandking_sand_storm", "Sand Storm" },
            { "sandking_caustic_finale", "Caustic Finale" },
            { "sandking_epicenter", "Epicenter" },
            { "special_bonus_unique_sand_king_3", "-30 Epicenter Attack Slow" },
            { "special_bonus_unique_sand_king_2", "+30 Sand Storm DPS" },
            { "special_bonus_unique_sand_king", "+2 Epicenter Pulses" },
            { "special_bonus_unique_sand_king_5", "+25 Epicenter Damage Per Pulse" },
            { "special_bonus_hp_regen_40", "+40 Health Regen" },
            { "special_bonus_unique_sand_king_4", "40% Sand Storm Slow and Blind" },
            { "storm_spirit_static_remnant", "Static Remnant" },
            { "storm_spirit_electric_vortex", "Electric Vortex" },
            { "storm_spirit_overload", "Overload" },
            { "storm_spirit_ball_lightning", "Ball Lightning" },
            { "special_bonus_unique_storm_spirit_6", "+24 Overload Damage" },
            { "special_bonus_mp_regen_250", "+2.5 Mana Regen" },
            { "special_bonus_unique_storm_spirit_5", "+65 Static Remnant Damage" },
            { "special_bonus_hp_325", "+325 Health" },
            { "special_bonus_unique_storm_spirit", "+0.4s Electric Vortex" },
            { "special_bonus_attack_speed_25", "+25 Attack Speed" },
            { "special_bonus_unique_storm_spirit_3", "Overload Pierces Immunity" },
            { "special_bonus_unique_storm_spirit_4", "600 Distance Auto Remnant in Ball Lightning" },
            { "sven_storm_bolt", "Storm Hammer" },
            { "sven_great_cleave", "Great Cleave" },
            { "sven_warcry", "Warcry" },
            { "sven_gods_strength", "God's Strength" },
            { "special_bonus_strength_7", "+7 Strength" },
            { "special_bonus_lifesteal_15", "15% Lifesteal" },
            { "special_bonus_unique_sven_3", "Storm Hammer Dispels Enemies" },
            { "special_bonus_unique_sven", "-5s Storm Hammer Cooldown" },
            { "special_bonus_unique_sven_2", "+32 STR God's Strength" },
            { "special_bonus_unique_sven_4", "+1s Storm Hammer Stun Duration" },
            { "tiny_avalanche", "Avalanche" },
            { "tiny_toss", "Toss" },
            { "tiny_tree_grab", "Tree Grab" },
            { "tiny_tree_channel", "Tree Volley" },
            { "tiny_grow", "Grow" },
            { "tiny_toss_tree", "Tree Throw" },
            { "special_bonus_movement_speed_15", "+15 Movement Speed" },
            { "special_bonus_unique_tiny", "+80 Avalanche Damage" },
            { "special_bonus_strength_16", "+16 Strength" },
            { "special_bonus_unique_tiny_5", "Toss Requires No Target" },
            { "special_bonus_unique_tiny_3", "-7s Avalanche Cooldown" },
            { "special_bonus_unique_tiny_2", "3 Toss Charges" },
            { "vengefulspirit_magic_missile", "Magic Missile" },
            { "vengefulspirit_wave_of_terror", "Wave of Terror" },
            { "vengefulspirit_command_aura", "Vengeance Aura" },
            { "vengefulspirit_nether_swap", "Nether Swap" },
            { "special_bonus_magic_resistance_12", "+12% Magic Resistance" },
            { "special_bonus_unique_vengeful_spirit_4", "-1 Wave of Terror Armor" },
            { "special_bonus_unique_vengeful_spirit_5", "-2.75s Magic Missile Cooldown" },
            { "special_bonus_unique_vengeful_spirit_1", "+160 Magic Missile Damage" },
            { "special_bonus_unique_vengeful_spirit_2", "+6 Vengeance Aura Attributes" },
            { "special_bonus_unique_vengeful_spirit_7", "Vengeance Aura Illusion Casts Spells" },
            { "special_bonus_unique_vengeful_spirit_3", "Magic Missile Pierces Spell Immunity" },
            { "windrunner_shackleshot", "Shackleshot" },
            { "windrunner_powershot", "Powershot" },
            { "windrunner_windrun", "Windrun" },
            { "windrunner_focusfire", "Focus Fire" },
            { "special_bonus_mp_regen_150", "+1.5 Mana Regen" },
            { "special_bonus_unique_windranger_9", "-2s Shackleshot Cooldown" },
            { "special_bonus_unique_windranger_3", "+100 Powershot Damage" },
            { "special_bonus_attack_range_100", "+100 Attack Range" },
            { "special_bonus_unique_windranger_6", "+0.8s Shackleshot Duration" },
            { "special_bonus_unique_windranger_8", "-16% Focus Fire Damage Reduction" },
            { "special_bonus_unique_windranger", "Windrun Grants Invisibility" },
            { "special_bonus_cooldown_reduction_25", "25% Cooldown Reduction" },
            { "zuus_arc_lightning", "Arc Lightning" },
            { "zuus_lightning_bolt", "Lightning Bolt" },
            { "zuus_static_field", "Static Field" },
            { "zuus_cloud", "Nimbus" },
            { "zuus_thundergods_wrath", "Thundergod's Wrath" },
            { "special_bonus_unique_zeus", "+1.2% Static Field Damage" },
            { "special_bonus_unique_zeus_3", "+0.4s Lightning Bolt Ministun" },
            { "special_bonus_cast_range_225", "+225 Cast Range" },
            { "special_bonus_unique_zeus_2", "+115 Arc Lightning Damage" },
            { "kunkka_torrent", "Torrent" },
            { "kunkka_tidebringer", "Tidebringer" },
            { "kunkka_x_marks_the_spot", "X Marks the Spot" },
            { "kunkka_torrent_storm", "Torrent Storm" },
            { "kunkka_ghostship", "Ghostship" },
            { "kunkka_return", "Return" },
            { "special_bonus_attack_damage_30", "+30 Damage" },
            { "special_bonus_hp_regen_8", "+8 Health Regen" },
            { "special_bonus_unique_kunkka_2", "+100 Torrent Damage" },
            { "special_bonus_unique_kunkka", "+80 Torrent AoE" },
            { "special_bonus_strength_18", "+18 Strength" },
            { "special_bonus_unique_kunkka_3", "Ghostship Fleet" },
            { "special_bonus_unique_kunkka_4", "+85% Tidebringer Cleave" },
            { "lina_dragon_slave", "Dragon Slave" },
            { "lina_light_strike_array", "Light Strike Array" },
            { "lina_fiery_soul", "Fiery Soul" },
            { "lina_laguna_blade", "Laguna Blade" },
            { "special_bonus_hp_300", "+300 Health" },
            { "special_bonus_unique_lina_3", "+110 Light Strike Array Damage" },
            { "special_bonus_spell_amplify_11", "+11% Spell Amplification" },
            { "special_bonus_unique_lina_2", "+24/1.5% Fiery Soul Per Stack" },
            { "special_bonus_unique_lina_1", "-5s Dragon Slave Cooldown" },
            { "special_bonus_attack_range_150", "+150 Attack Range" },
            { "lion_impale", "Earth Spike" },
            { "lion_voodoo", "Hex" },
            { "lion_mana_drain", "Mana Drain" },
            { "lion_finger_of_death", "Finger of Death" },
            { "special_bonus_attack_damage_70", "+70 Damage" },
            { "special_bonus_unique_lion_3", "+160 Finger of Death Damage" },
            { "special_bonus_unique_lion_6", "+15% Mana Drain Slow" },
            { "special_bonus_hp_400", "+400 Health" },
            { "special_bonus_unique_lion", "+2 Mana Drain Multi Target" },
            { "special_bonus_unique_lion_2", "+800 Earth Spike Range" },
            { "special_bonus_unique_lion_4", "+250 AoE Hex" },
            { "shadow_shaman_ether_shock", "Ether Shock" },
            { "shadow_shaman_voodoo", "Hex" },
            { "shadow_shaman_shackles", "Shackles" },
            { "shadow_shaman_mass_serpent_ward", "Mass Serpent Ward" },
            { "special_bonus_unique_shadow_shaman_6", "+100 Shackles Total Damage" },
            { "special_bonus_cast_range_100", "+100 Cast Range" },
            { "special_bonus_unique_shadow_shaman_5", "-4s Hex Cooldown" },
            { "special_bonus_unique_shadow_shaman_2", "+2s Shackles Duration" },
            { "special_bonus_unique_shadow_shaman_1", "+1 Serpent Wards Max HP" },
            { "special_bonus_unique_shadow_shaman_3", "+320 Ether Shock Damage" },
            { "special_bonus_unique_shadow_shaman_4", "+30 Wards Attack Damage" },
            { "slardar_sprint", "Guardian Sprint" },
            { "slardar_slithereen_crush", "Slithereen Crush" },
            { "slardar_bash", "Bash of the Deep" },
            { "slardar_amplify_damage", "Corrosive Haze" },
            { "special_bonus_hp_regen_6", "+6 Health Regen" },
            { "special_bonus_attack_damage_20", "+20 Damage" },
            { "special_bonus_hp_275", "+275 Health" },
            { "special_bonus_unique_slardar_2", "+60 Bash Damage" },
            { "special_bonus_lifesteal_25", "25% Lifesteal" },
            { "special_bonus_night_vision_800", "+800 Night Vision" },
            { "special_bonus_unique_slardar_4", "-3.5s Slithereen Crush Cooldown" },
            { "special_bonus_unique_slardar_3", "Corrosive Haze Undispellable" },
            { "tidehunter_gush", "Gush" },
            { "tidehunter_kraken_shell", "Kraken Shell" },
            { "tidehunter_anchor_smash", "Anchor Smash" },
            { "tidehunter_ravage", "Ravage" },
            { "special_bonus_unique_tidehunter_2", "+80 Gush Damage" },
            { "special_bonus_mp_regen_3", "+3 Mana Regen" },
            { "special_bonus_unique_tidehunter_3", "-20% Anchor Smash Damage Reduction" },
            { "special_bonus_unique_tidehunter_4", "+24 Kraken Shell Damage Block" },
            { "special_bonus_unique_tidehunter", "-4 Gush Armor" },
            { "special_bonus_cooldown_reduction_20", "20% Cooldown Reduction" },
            { "special_bonus_attack_damage_200", "+200 Damage" },
            { "witch_doctor_paralyzing_cask", "Paralyzing Cask" },
            { "witch_doctor_voodoo_restoration", "Voodoo Restoration" },
            { "witch_doctor_maledict", "Maledict" },
            { "witch_doctor_death_ward", "Death Ward" },
            { "special_bonus_attack_damage_60", "+60 Damage" },
            { "special_bonus_unique_witch_doctor_3", "+2 Cask Bounces" },
            { "special_bonus_unique_witch_doctor_6", "+80 Maledict AoE" },
            { "special_bonus_unique_witch_doctor_1", "+100 Death Ward Attack Range" },
            { "special_bonus_unique_witch_doctor_4", "+1 Maledict Tick" },
            { "special_bonus_unique_witch_doctor_2", "+1.2% Max Health Voodoo Restoration" },
            { "special_bonus_unique_witch_doctor_5", "+60 Death Ward Damage" },
            { "lich_frost_nova", "Frost Blast" },
            { "lich_frost_shield", "Frost Shield" },
            { "lich_sinister_gaze", "Sinister Gaze" },
            { "lich_chain_frost", "Chain Frost" },
            { "special_bonus_attack_damage_100", "+100 Damage" },
            { "special_bonus_unique_lich_3", "-3s Frost Blast Cooldown" },
            { "special_bonus_unique_lich_4", "+2.5s Frost Shield Duration" },
            { "special_bonus_unique_lich_1", "Frost Shield Provides +50 HP Regen" },
            { "special_bonus_unique_lich_5", "Chain Frost Unlimited Bounces" },
            { "riki_smoke_screen", "Smoke Screen" },
            { "riki_blink_strike", "Blink Strike" },
            { "riki_tricks_of_the_trade", "Tricks of the Trade" },
            { "riki_backstab", "Cloak and Dagger" },
            { "special_bonus_unique_riki_2", "-4s Smoke Screen Cooldown" },
            { "special_bonus_unique_riki_1", "+0.5 Backstab Multiplier" },
            { "special_bonus_unique_riki_3", "+475 Blink Strike Cast Range" },
            { "special_bonus_unique_riki_6", "-6 Tricks of the Trade Cooldown" },
            { "special_bonus_unique_riki_7", "+125 Smoke Screen AoE" },
            { "enigma_malefice", "Malefice" },
            { "enigma_demonic_conversion", "Demonic Conversion" },
            { "enigma_midnight_pulse", "Midnight Pulse" },
            { "enigma_black_hole", "Black Hole" },
            { "special_bonus_unique_enigma_4", "+150 Eidolon Attack Range" },
            { "special_bonus_unique_enigma_6", "+0.25s Malefice Stun Duration" },
            { "special_bonus_unique_enigma_3", "+50 Eidolon Damage" },
            { "special_bonus_unique_enigma_2", "+4 Malefice Instances" },
            { "special_bonus_unique_enigma", "+6 Demonic Conversion Eidolons" },
            { "tinker_laser", "Laser" },
            { "tinker_heat_seeking_missile", "Heat-Seeking Missile" },
            { "tinker_march_of_the_machines", "March of the Machines" },
            { "tinker_rearm", "Rearm" },
            { "special_bonus_spell_amplify_8", "+8% Spell Amplification" },
            { "special_bonus_unique_tinker_5", "+2.5s March of the Machines Duration" },
            { "special_bonus_mana_reduction_9", "+9% Manacost/Manaloss Reduction" },
            { "special_bonus_unique_tinker_2", "+8 March of the Machines Damage" },
            { "special_bonus_unique_tinker", "+80 Laser Damage" },
            { "special_bonus_unique_tinker_3", "+0.25s Heat-Seeking Missile Ministun" },
            { "sniper_shrapnel", "Shrapnel" },
            { "sniper_headshot", "Headshot" },
            { "sniper_take_aim", "Take Aim" },
            { "sniper_assassinate", "Assassinate" },
            { "special_bonus_cooldown_reduction_15", "15% Cooldown Reduction" },
            { "special_bonus_attack_damage_15", "+15 Damage" },
            { "special_bonus_unique_sniper_5", "-14% Shrapnel Slow" },
            { "special_bonus_unique_sniper_3", "+28 Knockback Distance Headshot" },
            { "special_bonus_unique_sniper_1", "+24 Shrapnel DPS" },
            { "special_bonus_unique_sniper_2", "+5 Shrapnel Charges" },
            { "necrolyte_death_pulse", "Death Pulse" },
            { "necrolyte_sadist", "Ghost Shroud" },
            { "necrolyte_heartstopper_aura", "Heartstopper Aura" },
            { "necrolyte_reapers_scythe", "Reaper's Scythe" },
            { "special_bonus_unique_necrophos_3", "+24% Ghost Shroud Slow" },
            { "special_bonus_unique_necrophos_4", "+32 Death Pulse Heal" },
            { "special_bonus_unique_necrophos_5", "+32% Heartstopper Regen Reduction" },
            { "special_bonus_unique_necrophos_2", "+0.5  Heartstopper Aura" },
            { "special_bonus_unique_necrophos", "-2s Death Pulse Cooldown" },
            { "warlock_fatal_bonds", "Fatal Bonds" },
            { "warlock_shadow_word", "Shadow Word" },
            { "warlock_upheaval", "Upheaval" },
            { "warlock_rain_of_chaos", "Chaotic Offering" },
            { "special_bonus_unique_warlock_5", "+3% Fatal Bonds Damage" },
            { "special_bonus_unique_warlock_3", "-5.5s Shadow Word Cooldown" },
            { "special_bonus_unique_warlock_4", "Summons a Golem on death" },
            { "special_bonus_unique_warlock_6", "300 Shadow Word AoE" },
            { "special_bonus_unique_warlock_2", "+20 Chaotic Offering Golems Armor" },
            { "special_bonus_unique_warlock_1", "80% Magic Resistance for Chaotic Offering Golems" },
            { "beastmaster_wild_axes", "Wild Axes" },
            { "beastmaster_call_of_the_wild_boar", "Call of the Wild Boar" },
            { "beastmaster_call_of_the_wild_hawk", "Call of the Wild Hawk" },
            { "beastmaster_inner_beast", "Inner Beast" },
            { "beastmaster_primal_roar", "Primal Roar" },
            { "special_bonus_unique_beastmaster_3", "-14s Hawks Cooldown" },
            { "special_bonus_unique_beastmaster_2", "+30 Boar Damage" },
            { "special_bonus_unique_beastmaster_4", "+20 Inner Beast Attack Speed" },
            { "special_bonus_unique_beastmaster", "+80 Wild Axes Damage" },
            { "queenofpain_shadow_strike", "Shadow Strike" },
            { "queenofpain_blink", "Blink" },
            { "queenofpain_scream_of_pain", "Scream Of Pain" },
            { "queenofpain_sonic_wave", "Sonic Wave" },
            { "special_bonus_cooldown_reduction_10", "10% Cooldown Reduction" },
            { "special_bonus_spell_lifesteal_25", "25% Spell Lifesteal" },
            { "special_bonus_unique_queen_of_pain", "525 AoE Shadow Strike" },
            { "special_bonus_unique_queen_of_pain_2", "Scream of Pain 1.2s Fear" },
            { "special_bonus_spell_block_18", "18s Spell Block" },
            { "venomancer_venomous_gale", "Venomous Gale" },
            { "venomancer_poison_sting", "Poison Sting" },
            { "venomancer_plague_ward", "Plague Ward" },
            { "venomancer_poison_nova", "Poison Nova" },
            { "special_bonus_unique_venomancer_3", "-6 Venomous Gale CD" },
            { "special_bonus_unique_venomancer_7", "+12s Plague Ward Duration" },
            { "special_bonus_unique_venomancer_5", "Gale Hero Impact Summons 2 Wards" },
            { "special_bonus_unique_venomancer_2", "-10% Poison Sting Slow" },
            { "special_bonus_unique_venomancer_4", "+5.5s Poison Nova Duration" },
            { "special_bonus_spell_lifesteal_12", "12% Spell Lifesteal" },
            { "special_bonus_unique_venomancer_6", "+640 Poison Nova AoE" },
            { "special_bonus_unique_venomancer", "2.6x Plague Ward HP/Damage" },
            { "faceless_void_time_walk", "Time Walk" },
            { "faceless_void_time_dilation", "Time Dilation" },
            { "faceless_void_time_lock", "Time Lock" },
            { "faceless_void_chronosphere", "Chronosphere" },
            { "special_bonus_unique_faceless_void_3", "+55 Time Lock Damage" },
            { "special_bonus_unique_faceless_void_5", "-1.2s Time Walk" },
            { "special_bonus_attack_speed_40", "+40 Attack Speed" },
            { "special_bonus_unique_faceless_void", "+350 Timewalk Cast Range" },
            { "special_bonus_unique_faceless_void_4", "+20% Backtrack" },
            { "special_bonus_unique_faceless_void_2", "+140 Chronosphere AoE" },
            { "skeleton_king_hellfire_blast", "Wraithfire Blast" },
            { "skeleton_king_vampiric_aura", "Vampiric Aura" },
            { "skeleton_king_mortal_strike", "Mortal Strike" },
            { "skeleton_king_reincarnation", "Reincarnation" },
            { "special_bonus_unique_wraith_king_9", "-1s Wraithfire Blast Cooldown" },
            { "special_bonus_unique_wraith_king_6", "+24 Skeletons Attack Damage" },
            { "special_bonus_unique_wraith_king_1", "No Reincarnation Manacost" },
            { "special_bonus_unique_wraith_king_5", "+6 Skeletons Spawned" },
            { "special_bonus_unique_wraith_king_2", "+20% Vampiric Aura Lifesteal" },
            { "special_bonus_unique_wraith_king_4", "Reincarnation Casts Wraithfire Blast" },
            { "death_prophet_carrion_swarm", "Crypt Swarm" },
            { "death_prophet_silence", "Silence" },
            { "death_prophet_spirit_siphon", "Spirit Siphon" },
            { "death_prophet_exorcism", "Exorcism" },
            { "special_bonus_unique_death_prophet_3", "+0.8% Max Health Spirit Siphon" },
            { "special_bonus_unique_death_prophet_2", "-2.5s Crypt Swarm Cooldown" },
            { "special_bonus_unique_death_prophet_4", "Exorcism Grants Haste" },
            { "special_bonus_unique_death_prophet", "+6 Exorcism Spirits" },
            { "phantom_assassin_stifling_dagger", "Stifling Dagger" },
            { "phantom_assassin_phantom_strike", "Phantom Strike" },
            { "phantom_assassin_blur", "Blur" },
            { "phantom_assassin_coup_de_grace", "Coup de Grace" },
            { "special_bonus_lifesteal_12", "12% Lifesteal" },
            { "special_bonus_cleave_25", "+25% Cleave" },
            { "special_bonus_corruption_3", "-3 Armor Corruption" },
            { "special_bonus_unique_phantom_assassin_3", "+30% Blur Evasion" },
            { "special_bonus_unique_phantom_assassin_4", "+100% Coup de Grace Critical Damage" },
            { "special_bonus_unique_phantom_assassin", "Triple Strike Stifling Dagger" },
            { "pugna_nether_blast", "Nether Blast" },
            { "pugna_decrepify", "Decrepify" },
            { "pugna_nether_ward", "Nether Ward" },
            { "pugna_life_drain", "Life Drain" },
            { "special_bonus_unique_pugna_4", "-0.8s Netherblast Cooldown" },
            { "special_bonus_unique_pugna_6", "+3 Nether Ward Health" },
            { "special_bonus_unique_pugna_1", "+20% Life Drain Heal" },
            { "special_bonus_unique_pugna_5", "+1.5s Decrepify Duration" },
            { "special_bonus_unique_pugna_2", "+160 Nether Blast Damage" },
            { "special_bonus_unique_pugna_3", "+1.5 Netherward Damage Per Mana" },
            { "templar_assassin_refraction", "Refraction" },
            { "templar_assassin_meld", "Meld" },
            { "templar_assassin_psi_blades", "Psi Blades" },
            { "templar_assassin_trap", "Trap" },
            { "templar_assassin_trap_teleport", "Psionic Projection" },
            { "templar_assassin_psionic_trap", "Psionic Trap" },
            { "special_bonus_evasion_15", "15% Evasion" },
            { "special_bonus_unique_templar_assassin_3", "+160 Psionic Trap Damage" },
            { "special_bonus_unique_templar_assassin_4", "Meld Dispels" },
            { "special_bonus_unique_templar_assassin_2", "-3 Meld Armor Reduction" },
            { "special_bonus_unique_templar_assassin_7", "1s Meld Hit Bash" },
            { "special_bonus_unique_templar_assassin", "+4 Refraction Instances" },
            { "viper_poison_attack", "Poison Attack" },
            { "viper_nethertoxin", "Nethertoxin" },
            { "viper_corrosive_skin", "Corrosive Skin" },
            { "viper_viper_strike", "Viper Strike" },
            { "special_bonus_spell_lifesteal_8", "8% Spell Lifesteal" },
            { "special_bonus_unique_viper_1", "+5 Corrosive Skin Stats" },
            { "special_bonus_unique_viper_2", "+80 Viper Strike DPS" },
            { "special_bonus_unique_viper_3", "Nethertoxin Silences" },
            { "special_bonus_unique_viper_4", "Poison Attack Affects Buildings" },
            { "luna_lucent_beam", "Lucent Beam" },
            { "luna_moon_glaive", "Moon Glaives" },
            { "luna_lunar_blessing", "Lunar Blessing" },
            { "luna_eclipse", "Eclipse" },
            { "special_bonus_cast_range_350", "+350 Cast Range" },
            { "special_bonus_unique_luna_2", "-3.5s Lucent Beam Cooldown" },
            { "special_bonus_all_stats_8", "+8 All Stats" },
            { "special_bonus_unique_luna_1", "+100 Lucent Beam Damage" },
            { "special_bonus_lifesteal_30", "30% Lifesteal" },
            { "special_bonus_unique_luna_5", "+0.2s Eclipse Lucent Ministun" },
            { "dragon_knight_breathe_fire", "Breathe Fire" },
            { "dragon_knight_dragon_tail", "Dragon Tail" },
            { "dragon_knight_dragon_blood", "Dragon Blood" },
            { "dragon_knight_elder_dragon_form", "Elder Dragon Form" },
            { "special_bonus_unique_dragon_knight_3", "-24% Breathe Fire Damage Reduction" },
            { "special_bonus_hp_350", "+350 Health" },
            { "special_bonus_strength_20", "+20 Strength" },
            { "special_bonus_unique_dragon_knight", "1.8x Dragon Blood HP Regen/Armor" },
            { "special_bonus_unique_dragon_knight_2", "+1.6s Dragon Tail" },
            { "dazzle_poison_touch", "Poison Touch" },
            { "dazzle_shallow_grave", "Shallow Grave" },
            { "dazzle_shadow_wave", "Shadow Wave" },
            { "dazzle_bad_juju", "Bad Juju" },
            { "special_bonus_attack_damage_50", "+50 Damage" },
            { "special_bonus_unique_dazzle_2", "+24 Shadow Wave Heal / Damage" },
            { "special_bonus_movement_speed_30", "+30 Movement Speed" },
            { "special_bonus_unique_dazzle_3", "+36 Poison Touch DPS" },
            { "special_bonus_unique_dazzle_1", "-32% Poison Touch Slow" },
            { "special_bonus_unique_dazzle_4", "+0.4 Bad Juju Armor Reduction" },
            { "rattletrap_battery_assault", "Battery Assault" },
            { "rattletrap_power_cogs", "Power Cogs" },
            { "rattletrap_rocket_flare", "Rocket Flare" },
            { "rattletrap_overclocking", "Overclocking" },
            { "rattletrap_hookshot", "Hookshot" },
            { "special_bonus_unique_clockwerk_3", "+24 Battery Assault Damage" },
            { "special_bonus_unique_clockwerk_4", "Rocket Flare True Sight" },
            { "special_bonus_unique_clockwerk_2", "+100 Rocket Flare Damage" },
            { "special_bonus_unique_clockwerk", "-0.25s Battery Assault Interval" },
            { "leshrac_split_earth", "Split Earth" },
            { "leshrac_diabolic_edict", "Diabolic Edict" },
            { "leshrac_lightning_storm", "Lightning Storm" },
            { "leshrac_pulse_nova", "Pulse Nova" },
            { "special_bonus_unique_leshrac_3", "+40 Pulse Nova Damage" },
            { "special_bonus_unique_leshrac_1", "+30 Diabolic Edict Explosions" },
            { "special_bonus_unique_leshrac_2", "+2.5s Lightning Storm Slow Duration" },
            { "furion_sprout", "Sprout" },
            { "furion_teleportation", "Teleportation" },
            { "furion_force_of_nature", "Nature's Call" },
            { "furion_wrath_of_nature", "Wrath of Nature" },
            { "special_bonus_unique_furion_5", "+15 Wrath of Nature Base Damage" },
            { "special_bonus_unique_furion_2", "+4 Treants Summoned" },
            { "special_bonus_unique_furion_3", "Removed Teleportation Cooldown" },
            { "special_bonus_unique_furion", "1.8x Treant HP/Damage" },
            { "life_stealer_rage", "Rage" },
            { "life_stealer_feast", "Feast" },
            { "life_stealer_open_wounds", "Open Wounds" },
            { "life_stealer_infest", "Infest" },
            { "life_stealer_consume", "Consume" },
            { "special_bonus_unique_lifestealer_2", "+40% Open Wounds Lifesteal" },
            { "special_bonus_unique_lifestealer_3", "+1.2% Feast Lifesteal" },
            { "special_bonus_unique_lifestealer", "+1.5s Rage Duration" },
            { "dark_seer_vacuum", "Vacuum" },
            { "dark_seer_ion_shell", "Ion Shell" },
            { "dark_seer_surge", "Surge" },
            { "dark_seer_wall_of_replica", "Wall of Replica" },
            { "special_bonus_evasion_10", "10% Evasion" },
            { "special_bonus_unique_dark_seer_2", "+60 Vacuum AoE" },
            { "special_bonus_hp_regen_10", "+10 Health Regen" },
            { "special_bonus_unique_dark_seer_5", "+100 Ion Shell Radius" },
            { "special_bonus_unique_dark_seer", "+60 Ion Shell Damage" },
            { "special_bonus_unique_dark_seer_4", "Parallel Wall" },
            { "special_bonus_unique_dark_seer_3", "400 AoE Surge" },
            { "clinkz_death_pact", "Death Pact" },
            { "clinkz_searing_arrows", "Searing Arrows" },
            { "clinkz_wind_walk", "Skeleton Walk" },
            { "clinkz_burning_army", "Burning Army" },
            { "special_bonus_agility_7", "+7 Agility" },
            { "special_bonus_strength_9", "+9 Strength" },
            { "special_bonus_unique_clinkz_5", "-30s Burning Army Cooldown" },
            { "special_bonus_unique_clinkz_1", "+12 Searing Arrows Damage" },
            { "special_bonus_unique_clinkz_6", "+325 Death Pact Health" },
            { "special_bonus_unique_clinkz_2", "+3s Skeleton Walk Attack Speed Duration" },
            { "special_bonus_unique_clinkz_3", "Searing Arrows Multishot" },
            { "omniknight_purification", "Purification" },
            { "omniknight_repel", "Heavenly Grace" },
            { "omniknight_degen_aura", "Degen Aura" },
            { "omniknight_guardian_angel", "Guardian Angel" },
            { "special_bonus_unique_omniknight_5", "+10 Heavenly Grace HP Regen" },
            { "special_bonus_unique_omniknight_6", "-2s Purification Cooldown" },
            { "special_bonus_unique_omniknight_2", "-10% Degen Aura" },
            { "special_bonus_unique_omniknight_1", "+160 Purification Damage/Heal" },
            { "special_bonus_unique_omniknight_3", "-6.5s Heavenly Grace Cooldown" },
            { "enchantress_impetus", "Impetus" },
            { "enchantress_enchant", "Enchant" },
            { "enchantress_natures_attendants", "Nature's Attendants" },
            { "enchantress_bunny_hop", "Sproink" },
            { "enchantress_untouchable", "Untouchable" },
            { "special_bonus_attack_damage_40", "+40 Damage" },
            { "special_bonus_unique_enchantress_2", "+6 Nature's Attendants Wisps" },
            { "special_bonus_unique_enchantress_3", "-65 Untouchable Slow" },
            { "special_bonus_unique_enchantress_1", "Enchant Affects Ancients" },
            { "special_bonus_unique_enchantress_4", "+6.5% Impetus Damage" },
            { "special_bonus_unique_enchantress_5", "+20 Nature's Attendants Heal" },
            { "huskar_inner_fire", "Inner Fire" },
            { "huskar_burning_spear", "Burning Spear" },
            { "huskar_berserkers_blood", "Berserker's Blood" },
            { "huskar_life_break", "Life Break" },
            { "special_bonus_unique_huskar_2", "+6 Burning Spears DPS" },
            { "special_bonus_unique_huskar_6", "+40% Berserker's Blood Regen" },
            { "special_bonus_unique_huskar", "+325 Life Break Cast Range" },
            { "special_bonus_unique_huskar_5", "Burning Spears Pure Damage" },
            { "night_stalker_void", "Void" },
            { "night_stalker_crippling_fear", "Crippling Fear" },
            { "night_stalker_hunter_in_the_night", "Hunter in the Night" },
            { "night_stalker_darkness", "Dark Ascension" },
            { "special_bonus_mp_150", "+150 Mana" },
            { "special_bonus_attack_damage_35", "+35 Damage" },
            { "special_bonus_unique_night_stalker_2", "+80 Hunter In The Night Attack Speed" },
            { "special_bonus_unique_night_stalker", "-60s Dark Ascension Cooldown" },
            { "broodmother_spawn_spiderlings", "Spawn Spiderlings" },
            { "broodmother_spin_web", "Spin Web" },
            { "broodmother_incapacitating_bite", "Incapacitating Bite" },
            { "broodmother_insatiable_hunger", "Insatiable Hunger" },
            { "special_bonus_unique_broodmother_3", "+100 Spawn Spiderlings Damage" },
            { "special_bonus_unique_broodmother_4", "+25 Spiders Attack Damage" },
            { "special_bonus_unique_broodmother_1", "+50 Insatiable Hunger Damage/Lifesteal" },
            { "special_bonus_unique_broodmother_2", "+350 Spiders Health" },
            { "bounty_hunter_shuriken_toss", "Shuriken Toss" },
            { "bounty_hunter_jinada", "Jinada" },
            { "bounty_hunter_wind_walk", "Shadow Walk" },
            { "bounty_hunter_track", "Track" },
            { "special_bonus_unique_bounty_hunter_2", "+50 Shuriken Toss Damage" },
            { "special_bonus_attack_speed_50", "+50 Attack Speed" },
            { "special_bonus_unique_bounty_hunter", "+50 Jinada Gold Steal" },
            { "special_bonus_evasion_40", "40% Evasion" },
            { "special_bonus_unique_bounty_hunter_3", "+250 Track Gold" },
            { "weaver_the_swarm", "The Swarm" },
            { "weaver_shukuchi", "Shukuchi" },
            { "weaver_geminate_attack", "Geminate Attack" },
            { "weaver_time_lapse", "Time Lapse" },
            { "special_bonus_unique_weaver_1", "+60 Shukuchi Damage" },
            { "special_bonus_agility_6", "+6 Agility" },
            { "special_bonus_mana_break_15", "+15 Mana Break" },
            { "special_bonus_strength_11", "+11 Strength" },
            { "special_bonus_unique_weaver_3", "+0.4 Swarm Armor Reduction" },
            { "special_bonus_unique_weaver_4", "+4 Swarm Attacks to Kill" },
            { "special_bonus_unique_weaver_2", "+160 Shukuchi Movement Speed" },
            { "special_bonus_unique_weaver_5", "+1 Geminate Attack" },
            { "jakiro_dual_breath", "Dual Breath" },
            { "jakiro_ice_path", "Ice Path" },
            { "jakiro_liquid_fire", "Liquid Fire" },
            { "jakiro_macropyre", "Macropyre" },
            { "special_bonus_attack_range_275", "+275 Attack Range" },
            { "special_bonus_unique_jakiro_2", "+25 Dual Breath Burn Damage" },
            { "special_bonus_unique_jakiro_4", "-50 Liquid Fire Attack Speed" },
            { "special_bonus_unique_jakiro_5", "+325 Dual Breath Range" },
            { "special_bonus_unique_jakiro_3", "Macropyre Pure and Pierces Immunity" },
            { "special_bonus_unique_jakiro", "+1s Ice Path Duration" },
            { "batrider_sticky_napalm", "Sticky Napalm" },
            { "batrider_flamebreak", "Flamebreak" },
            { "batrider_firefly", "Firefly" },
            { "batrider_flaming_lasso", "Flaming Lasso" },
            { "special_bonus_spell_amplify_5", "+5% Spell Amplification" },
            { "special_bonus_unique_batrider_3", "+2s Flamebreak Burn Duration" },
            { "special_bonus_hp_250", "+250 Health" },
            { "special_bonus_unique_batrider_1", "+6.5s Firefly Duration" },
            { "special_bonus_unique_batrider_2", "-8s Flamebreak Cooldown" },
            { "chen_penitence", "Penitence" },
            { "chen_holy_persuasion", "Holy Persuasion" },
            { "chen_divine_favor", "Divine Favor" },
            { "chen_hand_of_god", "Hand of God" },
            { "special_bonus_unique_chen_6", "-32s Divine Favor Cooldown" },
            { "special_bonus_unique_chen_5", "+16 Holy Persuasion Damage" },
            { "special_bonus_unique_chen_7", "-24s Hand of God Cooldown" },
            { "special_bonus_unique_chen_4", "+800 Holy Persuasion Minimum Health" },
            { "special_bonus_unique_chen_1", "+4 Holy Persuasion Max Units" },
            { "special_bonus_unique_chen_2", "+280 Hand of God Heal" },
            { "spectre_spectral_dagger", "Spectral Dagger" },
            { "spectre_desolate", "Desolate" },
            { "spectre_dispersion", "Dispersion" },
            { "spectre_reality", "Reality" },
            { "spectre_haunt_single", "Shadow Step" },
            { "spectre_haunt", "Haunt" },
            { "special_bonus_hp_regen_5", "+5 Health Regen" },
            { "special_bonus_unique_spectre_2", "+12 Desolate Damage" },
            { "special_bonus_unique_spectre", "-8s Spectral Dagger Cooldown" },
            { "special_bonus_unique_spectre_3", "+14% Spectral Dagger Slow/Bonus" },
            { "special_bonus_unique_spectre_4", "+32% Haunt Illusion Damage" },
            { "special_bonus_unique_spectre_5", "+5% Dispersion" },
            { "ancient_apparition_cold_feet", "Cold Feet" },
            { "ancient_apparition_ice_vortex", "Ice Vortex" },
            { "ancient_apparition_chilling_touch", "Chilling Touch" },
            { "ancient_apparition_ice_blast", "Ice Blast" },
            { "ancient_apparition_ice_blast_release", "Release" },
            { "special_bonus_unique_ancient_apparition_7", "140 Chilling Touch Attack Range" },
            { "special_bonus_unique_ancient_apparition_3", "-2s Ice Vortex Cooldown" },
            { "special_bonus_hp_regen_12", "+12 Health Regen" },
            { "special_bonus_unique_ancient_apparition_4", "-6% Ice Vortex Slow/Resistance" },
            { "special_bonus_unique_ancient_apparition_2", "+65 Chilling Touch Damage" },
            { "special_bonus_unique_ancient_apparition_6", "500 AoE Cold Feet" },
            { "special_bonus_unique_ancient_apparition_5", "+4% Ice Blast Kill Threshold" },
            { "doom_bringer_devour", "Devour" },
            { "doom_bringer_scorched_earth", "Scorched Earth" },
            { "doom_bringer_infernal_blade", "Infernal Blade" },
            { "doom_bringer_empty1", "Devoured Ability" },
            { "doom_bringer_empty2", "Devoured Ability" },
            { "doom_bringer_doom", "Doom" },
            { "special_bonus_unique_doom_4", "+16 Scorched Earth Damage" },
            { "special_bonus_unique_doom_6", "+13% Scorched Earth Movement Speed" },
            { "special_bonus_unique_doom_7", "+3 Doom Duration" },
            { "special_bonus_unique_doom_3", "+120 Devour Bonus Gold" },
            { "special_bonus_unique_doom_5", "+30 Doom DPS" },
            { "special_bonus_unique_doom_2", "Devour Can Target Ancients" },
            { "special_bonus_unique_doom_1", "+2.4% Infernal Blade Damage" },
            { "special_bonus_cleave_150", "+150% Cleave" },
            { "ursa_earthshock", "Earthshock" },
            { "ursa_overpower", "Overpower" },
            { "ursa_fury_swipes", "Fury Swipes" },
            { "ursa_enrage", "Enrage" },
            { "special_bonus_unique_ursa_4", "+20s Fury Swipes Reset Time" },
            { "special_bonus_unique_ursa_3", "+1.2s Enrage Duration" },
            { "special_bonus_unique_ursa", "+12 Fury Swipes Damage" },
            { "special_bonus_unique_ursa_5", "+480 AoE Earthshock" },
            { "special_bonus_unique_ursa_7", "+3 Overpower Attacks" },
            { "spirit_breaker_charge_of_darkness", "Charge of Darkness" },
            { "spirit_breaker_bulldoze", "Bulldoze" },
            { "spirit_breaker_greater_bash", "Greater Bash" },
            { "spirit_breaker_nether_strike", "Nether Strike" },
            { "special_bonus_night_vision_500", "+500 Night Vision" },
            { "special_bonus_unique_spirit_breaker_3", "+12% Greater Bash Damage" },
            { "special_bonus_unique_spirit_breaker_2", "-5.5s Bulldoze Cooldown" },
            { "special_bonus_unique_spirit_breaker_1", "+20% Greater Bash Chance" },
            { "special_bonus_hp_650", "+650 Health" },
            { "gyrocopter_rocket_barrage", "Rocket Barrage" },
            { "gyrocopter_homing_missile", "Homing Missile" },
            { "gyrocopter_flak_cannon", "Flak Cannon" },
            { "gyrocopter_call_down", "Call Down" },
            { "special_bonus_unique_gyrocopter_6", "+0.4s Homing Missile Stun Duration" },
            { "special_bonus_unique_gyrocopter_4", "-40s Call Down Cooldown" },
            { "special_bonus_unique_gyrocopter_3", "+12 Rocket Barrage Damage" },
            { "special_bonus_unique_gyrocopter_1", "3 Homing Missile Charges" },
            { "special_bonus_unique_gyrocopter_5", "Global Call Down" },
            { "alchemist_acid_spray", "Acid Spray" },
            { "alchemist_unstable_concoction", "Unstable Concoction" },
            { "alchemist_goblins_greed", "Greevil's Greed" },
            { "alchemist_chemical_rage", "Chemical Rage" },
            { "alchemist_unstable_concoction_throw", "Unstable Concoction Throw" },
            { "special_bonus_unique_alchemist", "-6s Unstable Concoction Cooldown" },
            { "special_bonus_cleave_30", "+30% Cleave" },
            { "special_bonus_unique_alchemist_2", "+350 Unstable Concoction Damage" },
            { "special_bonus_unique_alchemist_6", "+50 Chemical Rage Movement Speed" },
            { "special_bonus_unique_alchemist_4", "+40 Chemical Rage Regeneration" },
            { "invoker_quas", "Quas" },
            { "invoker_wex", "Wex" },
            { "invoker_exort", "Exort" },
            { "invoker_empty1", "Invoked Spell" },
            { "invoker_empty2", "Invoked Spell" },
            { "invoker_invoke", "Invoke" },
            { "invoker_cold_snap", "Cold Snap" },
            { "invoker_ghost_walk", "Ghost Walk" },
            { "invoker_tornado", "Tornado" },
            { "invoker_emp", "E.M.P." },
            { "invoker_alacrity", "Alacrity" },
            { "invoker_chaos_meteor", "Chaos Meteor" },
            { "invoker_sun_strike", "Sun Strike" },
            { "invoker_forge_spirit", "Forge Spirit" },
            { "invoker_ice_wall", "Ice Wall" },
            { "invoker_deafening_blast", "Deafening Blast" },
            { "special_bonus_unique_invoker_10", "-24s Ghost Walk Cooldown" },
            { "special_bonus_unique_invoker_6", "+50 Chaos Meteor Contact Damage" },
            { "special_bonus_unique_invoker_1", "2 Forged Spirits Summoned" },
            { "special_bonus_unique_invoker_9", "-8s Cold Snap Cooldown" },
            { "special_bonus_unique_invoker_3", "-8s Tornado Cooldown" },
            { "special_bonus_unique_invoker_5", "+40 Alacrity Damage/Speed" },
            { "special_bonus_unique_invoker_2", "Radial Deafening Blast" },
            { "special_bonus_unique_invoker_11", "+2 Forged Spirit Armor Reduction" },
            { "silencer_curse_of_the_silent", "Arcane Curse" },
            { "silencer_glaives_of_wisdom", "Glaives of Wisdom" },
            { "silencer_last_word", "Last Word" },
            { "silencer_global_silence", "Global Silence" },
            { "special_bonus_unique_silencer", "+20 Arcane Curse Damage" },
            { "special_bonus_unique_silencer_2", "+2 Permanent Intelligence Steal" },
            { "special_bonus_unique_silencer_6", "+15% Arcane Curse Slow" },
            { "special_bonus_unique_silencer_3", "+15% Glaives of Wisdom Damage" },
            { "special_bonus_unique_silencer_4", "+1.5s Global Silence" },
            { "obsidian_destroyer_arcane_orb", "Arcane Orb" },
            { "obsidian_destroyer_astral_imprisonment", "Astral Imprisonment" },
            { "obsidian_destroyer_equilibrium", "Essence Flux" },
            { "obsidian_destroyer_sanity_eclipse", "Sanity's Eclipse" },
            { "special_bonus_mp_250", "+250 Mana" },
            { "special_bonus_unique_outworld_devourer_4", "+0.1 Sanity's Eclipse Mana Difference Multiplier" },
            { "special_bonus_unique_outworld_devourer", "+1.6% Arcane Orb Damage" },
            { "lycan_summon_wolves", "Summon Wolves" },
            { "lycan_howl", "Howl" },
            { "lycan_feral_impulse", "Feral Impulse" },
            { "lycan_wolf_bite", "Wolf Bite" },
            { "lycan_shapeshift", "Shapeshift" },
            { "special_bonus_unique_lycan_3", "+10 Feral HP Regen" },
            { "special_bonus_unique_lycan_1", "+5s Shapeshift Duration" },
            { "special_bonus_unique_lycan_4", "+15% Feral Impulse Damage" },
            { "special_bonus_unique_lycan_5", "+32% Chance Shapeshift Critical Strike" },
            { "special_bonus_unique_lycan_2", "+2 Wolves Summoned" },
            { "brewmaster_thunder_clap", "Thunder Clap" },
            { "brewmaster_cinder_brew", "Cinder Brew" },
            { "brewmaster_drunken_brawler", "Drunken Brawler" },
            { "brewmaster_primal_split", "Primal Split" },
            { "special_bonus_unique_brewmaster_3", "+2.5s Thunder Clap Slow" },
            { "special_bonus_unique_brewmaster", "+1400 Health to Primal Split Units" },
            { "special_bonus_unique_brewmaster_2", "-65s Primal Split Cooldown" },
            { "special_bonus_unique_brewmaster_4", "+140% Drunken Brawler Critical Strike Damage" },
            { "shadow_demon_disruption", "Disruption" },
            { "shadow_demon_soul_catcher", "Soul Catcher" },
            { "shadow_demon_shadow_poison", "Shadow Poison" },
            { "shadow_demon_shadow_poison_release", "Shadow Poison Release" },
            { "shadow_demon_demonic_purge", "Demonic Purge" },
            { "special_bonus_intelligence_12", "+12 Intelligence" },
            { "special_bonus_unique_shadow_demon_4", "+20% Shadow Poison Damage" },
            { "special_bonus_unique_shadow_demon_2", "-5s Soul Catcher Cooldown" },
            { "special_bonus_unique_shadow_demon_3", "-1.25s Shadow Poison Cooldown" },
            { "special_bonus_unique_shadow_demon_1", "+400 Demonic Purge Damage" },
            { "special_bonus_unique_shadow_demon_7", "2 Charges of Disruption" },
            { "lone_druid_spirit_bear", "Summon Spirit Bear" },
            { "lone_druid_spirit_link", "Spirit Link" },
            { "lone_druid_savage_roar", "Savage Roar" },
            { "lone_druid_true_form", "True Form" },
            { "special_bonus_unique_lone_druid_11", "+25 Spirit Bear Movement Speed" },
            { "special_bonus_unique_lone_druid_4", "-10 Savage Roar Cooldown" },
            { "special_bonus_unique_lone_druid_2", "+8 Spirit Bear Armor" },
            { "special_bonus_unique_lone_druid_8", "-32s True Form Cooldown" },
            { "special_bonus_unique_lone_druid_9", "0 Entangle Cooldown" },
            { "special_bonus_unique_lone_druid_10", "-0.15 Spirit Bear Attack Time" },
            { "special_bonus_unique_lone_druid_7", "+1000 True Form Health" },
            { "chaos_knight_chaos_bolt", "Chaos Bolt" },
            { "chaos_knight_reality_rift", "Reality Rift" },
            { "chaos_knight_chaos_strike", "Chaos Strike" },
            { "chaos_knight_phantasm", "Phantasm" },
            { "special_bonus_unique_chaos_knight_4", "+8s Phantasm Duration" },
            { "special_bonus_unique_chaos_knight", "Reality Rift Pierces Spell Immune" },
            { "special_bonus_unique_chaos_knight_2", "-1.5s Chaos Strike Cooldown" },
            { "special_bonus_unique_chaos_knight_3", "+1.5 Max Chaos Bolt Duration" },
            { "meepo_earthbind", "Earthbind" },
            { "meepo_poof", "Poof" },
            { "meepo_ransack", "Ransack" },
            { "meepo_divided_we_stand", "Divided We Stand" },
            { "special_bonus_strength_6", "+6 Strength" },
            { "special_bonus_unique_meepo_2", "+30 Poof Damage" },
            { "special_bonus_unique_meepo_3", "-3s Earthbind Cooldown" },
            { "special_bonus_lifesteal_8", "8% Lifesteal" },
            { "special_bonus_unique_meepo", "-4s Poof Cooldown" },
            { "treant_natures_grasp", "Nature's Grasp" },
            { "treant_leech_seed", "Leech Seed" },
            { "treant_living_armor", "Living Armor" },
            { "treant_eyes_in_the_forest", "Eyes In The Forest" },
            { "treant_natures_guise", "Nature's Guise" },
            { "treant_overgrowth", "Overgrowth" },
            { "special_bonus_unique_treant_4", "Nature's Guise Invisibility" },
            { "special_bonus_unique_treant_8", "+48 Living Armor Heal" },
            { "special_bonus_unique_treant_9", "+24 Nature's Grasp Damage" },
            { "special_bonus_unique_treant_2", "+40 Leech Seed Damage/Heal" },
            { "special_bonus_unique_treant_11", "100 DPS Overgrowth" },
            { "special_bonus_unique_treant_7", "450 AoE Living Armor" },
            { "ogre_magi_fireblast", "Fireblast" },
            { "ogre_magi_ignite", "Ignite" },
            { "ogre_magi_bloodlust", "Bloodlust" },
            { "ogre_magi_unrefined_fireblast", "Unrefined Fireblast" },
            { "ogre_magi_multicast", "Multicast" },
            { "special_bonus_unique_ogre_magi_4", "+16 Ignite DPS" },
            { "special_bonus_attack_damage_80", "+80 Damage" },
            { "special_bonus_strength_30", "+30 Strength" },
            { "special_bonus_unique_ogre_magi", "+40 Bloodlust AS" },
            { "special_bonus_movement_speed_60", "+60 Movement Speed" },
            { "special_bonus_unique_ogre_magi_2", "+240 Fireblast Damage" },
            { "undying_decay", "Decay" },
            { "undying_soul_rip", "Soul Rip" },
            { "undying_tombstone", "Tombstone" },
            { "undying_flesh_golem", "Flesh Golem" },
            { "special_bonus_unique_undying", "+25 Tombstone Zombie Damage" },
            { "special_bonus_unique_undying_4", "+40 Decay Duration" },
            { "special_bonus_unique_undying_3", "Tombstone On Death" },
            { "special_bonus_unique_undying_5", "+4 Tombstone Attacks to Destroy" },
            { "special_bonus_reincarnation_300", "Gains Reincarnation 300 CD" },
            { "special_bonus_unique_undying_2", "-2s Decay Cooldown" },
            { "rubick_telekinesis", "Telekinesis" },
            { "rubick_fade_bolt", "Fade Bolt" },
            { "rubick_arcane_supremacy", "Arcane Supremacy" },
            { "rubick_empty1", "Stolen Spell" },
            { "rubick_empty2", "Stolen Spell" },
            { "rubick_spell_steal", "Spell Steal" },
            { "rubick_telekinesis_land", "Telekinesis Land" },
            { "special_bonus_unique_rubick_2", "-80 Fade Bolt Hero Attack" },
            { "special_bonus_unique_rubick_3", "-4s Fade Bolt Cooldown" },
            { "special_bonus_unique_rubick", "+240 Telekinesis Land Distance" },
            { "special_bonus_unique_rubick_4", "-12s Telekinesis Cooldown" },
            { "special_bonus_unique_rubick_5", "+40% Spell Amp For Stolen Spells" },
            { "disruptor_thunder_strike", "Thunder Strike" },
            { "disruptor_glimpse", "Glimpse" },
            { "disruptor_kinetic_field", "Kinetic Field" },
            { "disruptor_static_storm", "Static Storm" },
            { "special_bonus_magic_resistance_20", "+20% Magic Resistance" },
            { "special_bonus_unique_disruptor_3", "+30 Thunder Strike Damage" },
            { "special_bonus_unique_disruptor_2", "-3s Kinetic Field Cooldown" },
            { "special_bonus_unique_disruptor_6", "Kinetic Field Grants True Sight" },
            { "special_bonus_unique_disruptor", "+3 Thunder Strike Hits" },
            { "special_bonus_unique_disruptor_4", "-8s Glimpse Cooldown" },
            { "special_bonus_unique_disruptor_5", "+3s Kinetic Field Duration" },
            { "nyx_assassin_impale", "Impale" },
            { "nyx_assassin_mana_burn", "Mana Burn" },
            { "nyx_assassin_spiked_carapace", "Spiked Carapace" },
            { "nyx_assassin_burrow", "Burrow" },
            { "nyx_assassin_vendetta", "Vendetta" },
            { "nyx_assassin_unburrow", "Unburrow" },
            { "special_bonus_unique_nyx_4", "+0.25s Impale Stun Duration" },
            { "special_bonus_unique_nyx", "+60% Spiked Carapace Damage" },
            { "special_bonus_unique_nyx_2", "+140 Impale Damage" },
            { "special_bonus_agility_80", "+80 Agility" },
            { "special_bonus_unique_nyx_3", "Vendetta Unobstructed Pathing" },
            { "naga_siren_mirror_image", "Mirror Image" },
            { "naga_siren_ensnare", "Ensnare" },
            { "naga_siren_rip_tide", "Rip Tide" },
            { "naga_siren_song_of_the_siren", "Song of the Siren" },
            { "naga_siren_song_of_the_siren_cancel", "Song of the Siren End" },
            { "special_bonus_unique_naga_siren_4", "+9% Mirror Image Damage" },
            { "special_bonus_strength_13", "+13 Strength" },
            { "special_bonus_unique_naga_siren_2", "-9s Ensnare Cooldown" },
            { "special_bonus_unique_naga_siren", "+1 Mirror Image Illusion" },
            { "special_bonus_evasion_25", "25% Evasion" },
            { "special_bonus_unique_naga_siren_3", "-5 Rip Tide Armor" },
            { "keeper_of_the_light_illuminate", "Illuminate" },
            { "keeper_of_the_light_blinding_light", "Blinding Light" },
            { "keeper_of_the_light_chakra_magic", "Chakra Magic" },
            { "keeper_of_the_light_will_o_wisp", "Will-O-Wisp" },
            { "keeper_of_the_light_illuminate_end", "Release Illuminate" },
            { "keeper_of_the_light_spirit_form_illuminate", "Illuminate" },
            { "keeper_of_the_light_spirit_form_illuminate_end", "Release Illuminate" },
            { "special_bonus_unique_keeper_of_the_light_5", "-2.5s Blinding Light Cooldown" },
            { "special_bonus_unique_keeper_of_the_light_3", "+2 Will-O-Wisp Flicker" },
            { "special_bonus_cast_range_200", "+200 Cast Range" },
            { "special_bonus_unique_keeper_of_the_light_6", "+150 Will-O-Wisp AOE" },
            { "special_bonus_unique_keeper_of_the_light_2", "+250 Chakra Magic Mana" },
            { "special_bonus_unique_keeper_of_the_light_4", "+3 Will-O-Wisp Health Count" },
            { "special_bonus_unique_keeper_of_the_light", "+160 Illuminate Damage/Heal" },
            { "wisp_tether", "Tether" },
            { "wisp_spirits", "Spirits" },
            { "wisp_overcharge", "Overcharge" },
            { "wisp_relocate", "Relocate" },
            { "wisp_tether_break", "Break Tether" },
            { "wisp_spirits_in", "Spirits Movement" },
            { "special_bonus_hp_regen_4", "+4 Health Regen" },
            { "special_bonus_unique_wisp_3", "+325 Spirits Max Range" },
            { "special_bonus_unique_wisp", "+60 Spirits Hero Damage" },
            { "special_bonus_unique_wisp_6", "-25s Relocate Cooldown" },
            { "special_bonus_hp_700", "+700 Health" },
            { "special_bonus_unique_wisp_4", "Attack Tethered Ally's Target" },
            { "visage_grave_chill", "Grave Chill" },
            { "visage_soul_assumption", "Soul Assumption" },
            { "visage_gravekeepers_cloak", "Gravekeeper's Cloak" },
            { "visage_stone_form_self_cast", "Stone Form" },
            { "visage_summon_familiars", "Summon Familiars" },
            { "special_bonus_corruption_25", "-2.5 Armor Corruption" },
            { "special_bonus_unique_visage_3", "Soul Assumption Hits 2 Targets" },
            { "special_bonus_unique_visage_4", "+20 Soul Assumption Damage Per Charge" },
            { "special_bonus_unique_visage_2", "+40 Familiars Movement Speed" },
            { "special_bonus_unique_visage_5", "+5 Gravekeeper's Cloak Stacks" },
            { "special_bonus_unique_visage_6", "+1 Familiar" },
            { "slark_dark_pact", "Dark Pact" },
            { "slark_pounce", "Pounce" },
            { "slark_essence_shift", "Essence Shift" },
            { "slark_shadow_dance", "Shadow Dance" },
            { "special_bonus_unique_slark_2", "+120 Dark Pact Damage" },
            { "special_bonus_unique_slark", "+0.8s Pounce Leash" },
            { "special_bonus_unique_slark_3", "+1s Shadow Dance Duration" },
            { "special_bonus_unique_slark_4", "+65 Essence Shift Duration" },
            { "medusa_split_shot", "Split Shot" },
            { "medusa_mystic_snake", "Mystic Snake" },
            { "medusa_mana_shield", "Mana Shield" },
            { "medusa_stone_gaze", "Stone Gaze" },
            { "special_bonus_unique_medusa_3", "+32% Mystic Snake Mana Gain" },
            { "special_bonus_unique_medusa_5", "-3s Mystic Snake Cooldown" },
            { "special_bonus_unique_medusa", "+2s Stone Gaze Duration" },
            { "special_bonus_mp_800", "+800 Mana" },
            { "special_bonus_unique_medusa_4", "Split Shot Uses Modifiers" },
            { "troll_warlord_berserkers_rage", "Berserker's Rage" },
            { "troll_warlord_whirling_axes_ranged", "Whirling Axes (Ranged)" },
            { "troll_warlord_whirling_axes_melee", "Whirling Axes (Melee)" },
            { "troll_warlord_fervor", "Fervor" },
            { "troll_warlord_battle_trance", "Battle Trance" },
            { "special_bonus_unique_troll_warlord_2", "+3 Max Fervor Stacks" },
            { "special_bonus_unique_troll_warlord_3", "+70 Whirling Axes Damage" },
            { "special_bonus_evasion_20", "20% Evasion" },
            { "special_bonus_unique_troll_warlord", "-5s Whirling Axes Cooldown" },
            { "special_bonus_unique_troll_warlord_4", "Battle Trance Strong Dispels" },
            { "centaur_hoof_stomp", "Hoof Stomp" },
            { "centaur_double_edge", "Double Edge" },
            { "centaur_return", "Retaliate" },
            { "centaur_stampede", "Stampede" },
            { "special_bonus_attack_base_damage_25", "+25 Base Damage" },
            { "special_bonus_unique_centaur_4", "+40% Double Edge Strength Damage" },
            { "special_bonus_unique_centaur_3", "+70 Retaliate Damage" },
            { "special_bonus_unique_centaur_5", "-20s Stampede Cooldown" },
            { "special_bonus_unique_centaur_1", "Gains Retaliate Aura" },
            { "special_bonus_unique_centaur_2", "+1s Hoof Stomp Duration" },
            { "magnataur_shockwave", "Shockwave" },
            { "magnataur_empower", "Empower" },
            { "magnataur_skewer", "Skewer" },
            { "magnataur_reverse_polarity", "Reverse Polarity" },
            { "special_bonus_unique_magnus_4", "+100 Shockwave Damage" },
            { "special_bonus_unique_magnus_3", "+425 Skewer Range" },
            { "special_bonus_unique_magnus_2", "+12% Empower Damage/Cleave" },
            { "special_bonus_unique_magnus_5", "+0.8s Reverse Polarity Stun Duration" },
            { "shredder_whirling_death", "Whirling Death" },
            { "shredder_timber_chain", "Timber Chain" },
            { "shredder_reactive_armor", "Reactive Armor" },
            { "shredder_chakram_2", "Second Chakram" },
            { "shredder_chakram", "Chakram" },
            { "shredder_return_chakram", "Return Chakram" },
            { "shredder_return_chakram_2", "Return Chakram" },
            { "special_bonus_unique_timbersaw_2", "+6 Reactive Armor Stacks" },
            { "special_bonus_unique_timbersaw", "+10% Whirling Death Attribute Reduction" },
            { "special_bonus_unique_timbersaw_3", "+1125 Timber Chain Range" },
            { "bristleback_viscous_nasal_goo", "Viscous Nasal Goo" },
            { "bristleback_quill_spray", "Quill Spray" },
            { "bristleback_bristleback", "Bristleback" },
            { "bristleback_warpath", "Warpath" },
            { "special_bonus_unique_bristleback", "+5 Max Goo Stacks" },
            { "special_bonus_unique_bristleback_2", "+20 Quill Stack Damage" },
            { "special_bonus_spell_lifesteal_13", "13% Spell Lifesteal" },
            { "special_bonus_unique_bristleback_3", "+24 Warpath Damage Per Stack" },
            { "tusk_ice_shards", "Ice Shards" },
            { "tusk_snowball", "Snowball" },
            { "tusk_tag_team", "Tag Team" },
            { "tusk_walrus_kick", "Walrus Kick" },
            { "tusk_walrus_punch", "Walrus PUNCH!" },
            { "tusk_launch_snowball", "Launch Snowball" },
            { "special_bonus_unique_tusk_7", "+0.4s Walrus Punch Stun Duration" },
            { "special_bonus_unique_tusk_2", "+120 Snowball Damage" },
            { "special_bonus_unique_tusk_5", "-6s Ice Shards Cooldown" },
            { "special_bonus_unique_tusk", "+80% Walrus Punch Crit" },
            { "special_bonus_unique_tusk_4", "12% Chance Walrus Punch" },
            { "special_bonus_unique_tusk_6", "-6s Snowball Cooldown" },
            { "skywrath_mage_arcane_bolt", "Arcane Bolt" },
            { "skywrath_mage_concussive_shot", "Concussive Shot" },
            { "skywrath_mage_ancient_seal", "Ancient Seal" },
            { "skywrath_mage_mystic_flare", "Mystic Flare" },
            { "special_bonus_intelligence_10", "+10 Intelligence" },
            { "special_bonus_unique_skywrath", "-7s Ancient Seal Cooldown" },
            { "special_bonus_unique_skywrath_2", "+1 Arcane Bolt Per Cast" },
            { "special_bonus_unique_skywrath_4", "Global Concussive Shot" },
            { "special_bonus_unique_skywrath_3", "-12% Ancient Seal Magic Resistance Reduction" },
            { "special_bonus_unique_skywrath_6", "Arcane Bolt Pierces Spell Immunity" },
            { "special_bonus_unique_skywrath_5", "+480 Mystic Flare Damage" },
            { "abaddon_death_coil", "Mist Coil" },
            { "abaddon_aphotic_shield", "Aphotic Shield" },
            { "abaddon_frostmourne", "Curse of Avernus" },
            { "abaddon_borrowed_time", "Borrowed Time" },
            { "special_bonus_unique_abaddon_2", "+48 Mist Coil Heal/Damage" },
            { "special_bonus_unique_abaddon", "+180 Aphotic Shield Health" },
            { "special_bonus_unique_abaddon_4", "340 AoE Mist Coil" },
            { "elder_titan_echo_stomp", "Echo Stomp" },
            { "elder_titan_ancestral_spirit", "Astral Spirit" },
            { "elder_titan_natural_order", "Natural Order" },
            { "elder_titan_earth_splitter", "Earth Splitter" },
            { "elder_titan_return_spirit", "Return Astral Spirit" },
            { "special_bonus_unique_elder_titan", "+25 Astral Spirit Hero Attack" },
            { "special_bonus_attack_speed_55", "+55 Attack Speed" },
            { "special_bonus_unique_elder_titan_2", "+100 Echo Stomp Damage" },
            { "special_bonus_unique_elder_titan_3", "-60 Earth Splitter Cooldown" },
            { "special_bonus_unique_elder_titan_4", "+450 Echo Stomp Wake Damage" },
            { "legion_commander_overwhelming_odds", "Overwhelming Odds" },
            { "legion_commander_press_the_attack", "Press The Attack" },
            { "legion_commander_moment_of_courage", "Moment of Courage" },
            { "legion_commander_duel", "Duel" },
            { "special_bonus_unique_legion_commander_6", "-4s Overwhelming Odds Cooldown" },
            { "special_bonus_unique_legion_commander_3", "+8% Moment Proc Chance" },
            { "special_bonus_unique_legion_commander", "+32 Duel Damage Bonus" },
            { "special_bonus_unique_legion_commander_5", "275 AoE Press The Attack" },
            { "techies_land_mines", "Proximity Mines" },
            { "techies_stasis_trap", "Stasis Trap" },
            { "techies_suicide", "Blast Off!" },
            { "techies_focused_detonate", "Focused Detonate" },
            { "techies_minefield_sign", "Minefield Sign" },
            { "techies_remote_mines", "Remote Mines" },
            { "special_bonus_unique_techies_3", "-3s Proximity Mines Cooldown" },
            { "special_bonus_unique_techies", "+240 Blast Off! Damage" },
            { "special_bonus_mp_regen_5", "+5 Mana Regen" },
            { "special_bonus_unique_techies_5", "-22s Blast Off! Cooldown" },
            { "special_bonus_attack_damage_251", "+251 Damage" },
            { "special_bonus_unique_techies_4", "+60 Mines Movement Speed" },
            { "ember_spirit_searing_chains", "Searing Chains" },
            { "ember_spirit_sleight_of_fist", "Sleight of Fist" },
            { "ember_spirit_flame_guard", "Flame Guard" },
            { "ember_spirit_activate_fire_remnant", "Activate Fire Remnant" },
            { "ember_spirit_fire_remnant", "Fire Remnant" },
            { "special_bonus_unique_ember_spirit_1", "+280 Flame Guard Absorption" },
            { "special_bonus_unique_ember_spirit_3", "+50 Flame Guard DPS" },
            { "special_bonus_unique_ember_spirit_2", "+0.8s Searing Chains" },
            { "special_bonus_unique_ember_spirit_6", "+65 Sleight of Fist Hero Damage" },
            { "special_bonus_unique_ember_spirit_4", "2 Sleight of Fist Charges" },
            { "special_bonus_unique_ember_spirit_5", "-12 Remnant Charge Restore Time" },
            { "earth_spirit_boulder_smash", "Boulder Smash" },
            { "earth_spirit_rolling_boulder", "Rolling Boulder" },
            { "earth_spirit_geomagnetic_grip", "Geomagnetic Grip" },
            { "earth_spirit_stone_caller", "Stone Remnant" },
            { "earth_spirit_petrify", "Enchant Remnant" },
            { "earth_spirit_magnetize", "Magnetize" },
            { "special_bonus_unique_earth_spirit_4", "+325 Rolling Boulder Distance" },
            { "special_bonus_unique_earth_spirit", "+120 Rolling Boulder Damage" },
            { "special_bonus_spell_amplify_16", "+16% Spell Amplification" },
            { "special_bonus_unique_earth_spirit_5", "+3 Geomagnetic Grip Silence" },
            { "special_bonus_unique_earth_spirit_2", "Geomagnetic Grip Targets Allies" },
            { "special_bonus_unique_earth_spirit_3", "+0.6s Rolling Boulder Stun Duration" },
            { "abyssal_underlord_firestorm", "Firestorm" },
            { "abyssal_underlord_pit_of_malice", "Pit of Malice" },
            { "abyssal_underlord_atrophy_aura", "Atrophy Aura" },
            { "abyssal_underlord_dark_rift", "Dark Rift" },
            { "abyssal_underlord_cancel_dark_rift", "Cancel Dark Rift" },
            { "special_bonus_unique_underlord_2", "+14 Firestorm Wave Damage" },
            { "special_bonus_cast_range_175", "+175 Cast Range" },
            { "special_bonus_unique_underlord_3", "+5 Atrophy Permanent Bonus Damage " },
            { "special_bonus_unique_underlord", "+0.65s Pit of Malice Root" },
            { "special_bonus_unique_underlord_4", "20% Firestorm Building Damage" },
            { "terrorblade_reflection", "Reflection" },
            { "terrorblade_conjure_image", "Conjure Image" },
            { "terrorblade_metamorphosis", "Metamorphosis" },
            { "terrorblade_terror_wave", "Terror Wave" },
            { "terrorblade_sunder", "Sunder" },
            { "special_bonus_unique_terrorblade_5", "+8s Conjure Image Duration" },
            { "special_bonus_unique_terrorblade", "-32s Sunder Cooldown" },
            { "special_bonus_unique_terrorblade_3", "+240 Metamorphosis Attack Range" },
            { "phoenix_icarus_dive", "Icarus Dive" },
            { "phoenix_fire_spirits", "Fire Spirits" },
            { "phoenix_sun_ray", "Sun Ray" },
            { "phoenix_sun_ray_toggle_move", "Toggle Movement" },
            { "phoenix_supernova", "Supernova" },
            { "phoenix_launch_fire_spirit", "Launch Fire Spirit" },
            { "phoenix_icarus_dive_stop", "Stop Icarus Dive" },
            { "phoenix_sun_ray_stop", "Stop Sun Ray" },
            { "special_bonus_unique_phoenix_6", "+14% Icarus Dive Slow" },
            { "special_bonus_unique_phoenix_3", "+25 Fire Spirits DPS" },
            { "special_bonus_unique_phoenix_4", "+1100 Icarus Dive Cast Range" },
            { "special_bonus_unique_phoenix_7", "Sun Ray During Supernova" },
            { "special_bonus_unique_phoenix_1", "+3 Supernova Hit Count" },
            { "special_bonus_unique_phoenix_5", "+1.5% Max Health Sun Ray Damage" },
            { "oracle_fortunes_end", "Fortune's End" },
            { "oracle_fates_edict", "Fate's Edict" },
            { "oracle_purifying_flames", "Purifying Flames" },
            { "oracle_false_promise", "False Promise" },
            { "special_bonus_unique_oracle_2", "+0.4s Fortune's End Duration" },
            { "special_bonus_unique_oracle_5", "-0.8s Purifying Flames Cooldown" },
            { "special_bonus_unique_oracle_6", "-20s False Promise Cooldown" },
            { "special_bonus_unique_oracle_4", "False Promise Invisibility" },
            { "special_bonus_unique_oracle_3", "-4s Fate's Edict Cooldown" },
            { "special_bonus_unique_oracle", "+1.5 False Promise Duration" },
            { "winter_wyvern_arctic_burn", "Arctic Burn" },
            { "winter_wyvern_splinter_blast", "Splinter Blast" },
            { "winter_wyvern_cold_embrace", "Cold Embrace" },
            { "winter_wyvern_winters_curse", "Winter's Curse" },
            { "special_bonus_unique_winter_wyvern_5", "+1% Cold Embrace Heal" },
            { "special_bonus_night_vision_400", "+400 Night Vision" },
            { "special_bonus_unique_winter_wyvern_1", "+12% Arctic Burn Slow" },
            { "special_bonus_unique_winter_wyvern_2", "-4s Cold Embrace Cooldown" },
            { "special_bonus_unique_winter_wyvern_3", "+1.2s Winter's Curse Duration" },
            { "special_bonus_unique_winter_wyvern_4", "Splinter Blast 1.5s Stun" },
            { "arc_warden_flux", "Flux" },
            { "arc_warden_magnetic_field", "Magnetic Field" },
            { "arc_warden_spark_wraith", "Spark Wraith" },
            { "arc_warden_scepter", "Rune Forge" },
            { "arc_warden_tempest_double", "Tempest Double" },
            { "special_bonus_cooldown_reduction_6", "6% Cooldown Reduction" },
            { "special_bonus_unique_arc_warden_5", "+325 Flux Cast Range" },
            { "special_bonus_unique_arc_warden_3", "-1.5s Spark Wraith Cooldown" },
            { "special_bonus_unique_arc_warden", "+250 Spark Wraith Damage" },
            { "monkey_king_boundless_strike", "Boundless Strike" },
            { "monkey_king_tree_dance", "Tree Dance" },
            { "monkey_king_primal_spring", "Primal Spring" },
            { "monkey_king_jingu_mastery", "Jingu Mastery" },
            { "monkey_king_mischief", "Mischief" },
            { "monkey_king_wukongs_command", "Wukong's Command" },
            { "monkey_king_primal_spring_early", "Spring Early" },
            { "monkey_king_untransform", "Revert Form" },
            { "special_bonus_unique_monkey_king_5", "+325 Tree Dance Vision AoE" },
            { "special_bonus_unique_monkey_king_7", "+475 Tree Dance Cast Range" },
            { "special_bonus_unique_monkey_king_2", "+80 Jingu Mastery Damage" },
            { "special_bonus_unique_monkey_king", "+40% Boundless Strike Crit" },
            { "special_bonus_unique_monkey_king_3", "+320 Primal Spring Damage" },
            { "special_bonus_unique_monkey_king_4", "+100 Armor Wukong's Command" },
            { "special_bonus_unique_monkey_king_6", "Additional Wukong's Command Ring" },
            { "dark_willow_bramble_maze", "Bramble Maze" },
            { "dark_willow_shadow_realm", "Shadow Realm" },
            { "dark_willow_cursed_crown", "Cursed Crown" },
            { "dark_willow_bedlam", "Bedlam" },
            { "dark_willow_terrorize", "Terrorize" },
            { "special_bonus_unique_dark_willow_4", "+32 Bedlam Damage" },
            { "special_bonus_unique_dark_willow_3", "-10s Bramble Maze CD" },
            { "special_bonus_attack_speed_110", "+110 Attack Speed" },
            { "special_bonus_unique_dark_willow_2", "+1.3 Terrorize Duration" },
            { "pangolier_swashbuckle", "Swashbuckle" },
            { "pangolier_shield_crash", "Shield Crash" },
            { "pangolier_lucky_shot", "Lucky Shot" },
            { "pangolier_gyroshell", "Rolling Thunder" },
            { "pangolier_gyroshell_stop", "Stop Rolling" },
            { "special_bonus_unique_pangolier_7", "+350 Swashbuckle Slash Range" },
            { "special_bonus_unique_pangolier_2", "2.5s Shield Crash CD in Ball" },
            { "special_bonus_unique_pangolier_6", "+3s Rolling Thunder Duration" },
            { "special_bonus_unique_pangolier_3", "+30 Swashbuckle Damage" },
            { "special_bonus_unique_pangolier_4", "-2.5s Swashbuckle Cooldown" },
            { "special_bonus_unique_pangolier_5", "-28s Rolling Thunder Cooldown" },
            { "grimstroke_dark_artistry", "Stroke of Fate" },
            { "grimstroke_ink_creature", "Phantom's Embrace" },
            { "grimstroke_spirit_walk", "Ink Swell" },
            { "grimstroke_scepter", "Dark Portrait" },
            { "grimstroke_soul_chain", "Soulbind" },
            { "special_bonus_unique_grimstroke_5", "+80 Ink Swell Max Damage" },
            { "special_bonus_spell_amplify_15", "+15% Spell Amplification" },
            { "special_bonus_unique_grimstroke_3", "+650 Stroke of Fate Cast Range" },
            { "special_bonus_unique_grimstroke_4", "+3 Hits to Kill Phantom" },
            { "special_bonus_unique_grimstroke_1", "+150 Ink Swell Radius" },
            { "special_bonus_unique_grimstroke_2", "+40% Stroke of Fate Damage" },
            { "void_spirit_aether_remnant", "Aether Remnant" },
            { "void_spirit_dissimilate", "Dissimilate" },
            { "void_spirit_resonant_pulse", "Resonant Pulse" },
            { "void_spirit_astral_step", "Astral Step" },
            { "special_bonus_unique_void_spirit_7", "Remnant Provides 475 Truesight" },
            { "special_bonus_unique_void_spirit_4", "+80 Resonant Pulse Damage" },
            { "special_bonus_spell_amplify_14", "+14% Spell Amplification" },
            { "special_bonus_unique_void_spirit_1", "-5.5 Astral Step Charge Restore Time" },
            { "special_bonus_unique_void_spirit_8", "Astral Step 160% Crit" },
            { "special_bonus_unique_void_spirit_3", "Dissimilate Stuns for 2.5s" },
            { "snapfire_scatterblast", "Scatterblast" },
            { "snapfire_firesnap_cookie", "Firesnap Cookie" },
            { "snapfire_lil_shredder", "Lil' Shredder" },
            { "snapfire_gobble_up", "Gobble Up" },
            { "snapfire_spit_creep", "Spit Out" },
            { "snapfire_mortimer_kisses", "Mortimer Kisses" },
            { "special_bonus_unique_snapfire_5", "Firesnap Cookie Restores 200 Health" },
            { "special_bonus_unique_snapfire_7", "+48 Scatterblast Damage" },
            { "special_bonus_unique_snapfire_6", "Lil' Shredder Uses Your Attack Damage" },
            { "special_bonus_unique_snapfire_4", "+20% Mortimer Kisses Movement Slow" },
            { "special_bonus_unique_snapfire_3", "Scatterblast Applies 2.5s Disarm" },
            { "special_bonus_unique_snapfire_1", "+6 Mortimer Kisses Launched" },
            { "mars_spear", "Spear of Mars" },
            { "mars_gods_rebuke", "God's Rebuke" },
            { "mars_bulwark", "Bulwark" },
            { "mars_arena_of_blood", "Arena Of Blood" },
            { "special_bonus_unique_mars_spear_cooldown", "-2s Spear Cooldown" },
            { "special_bonus_unique_mars_spear_bonus_damage", "Spear Of Mars +160 Damage" },
            { "special_bonus_unique_mars_spear_stun_duration", "+0.8s Spear Stun" },
            { "special_bonus_unique_mars_gods_rebuke_extra_crit", "God's Rebuke +65% Crit" },
            { "special_bonus_unique_mars_arena_of_blood_hp_regen", "Arena Of Blood Grants Team +80 HP Regen" },
        };

        public string GetAbilityName(string name)
        {
            if (this.names.TryGetValue(name, out var abilityName))
            {
                return abilityName;
            }

            Logger.Error("NoAbilityName", name);
            return "unknown";
        }
    }
}